### PR TITLE
Add Rod Server component to expose a REST API

### LINKED ISSUE #8: Setup rod as a service than can be deployed to a machine
Rod should be a service in a machine (or group of machines).
It also needs an API for clients (e.g. management client) to interact with, say a  REST API.

### PR DESCRIPTION
**Pull request by miguelaferreira**
Closes #8

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
@miguelaferreira 

Coverage complains... Could you have a look?

I already reviewed the code, but could not find the failing issue it's complaining.

**Comment by miguelaferreira** [comment]
Coveralls complaints because coverage it went down.
I will add the missing tests, and fix a few more things.

**Comment by miguelaferreira** [comment]
@wilderrodrigues coverage is good again :)

**Comment by miguelaferreira** [comment]
ping ping ping @wilderrodrigues

**Pull request merged**
